"""SessionStart hook: make sure today's daily note exists, check the whole
vault (this also catches edits made on the phone, which bypass every other
hook), and hand Claude the current state so it never has to remember to look.
Whatever this prints is added to Claude's context."""
from __future__ import annotations

import sys
import time
from pathlib import Path

sys.dont_write_bytecode = True  # keep __pycache__ out of iCloud
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import lib  # noqa: E402
import vault  # noqa: E402

MAX_PROBLEMS = 15


def main() -> None:
    lib.setup_io()
    if lib.VAULT is None:
        return
    data = lib.read_hook_input()
    sid = data.get("session_id", "")
    state = lib.load_state(sid)
    state.setdefault("started", time.time())
    lib.save_state(sid, state)

    path, _ = vault.create_daily()
    d = lib.today()
    out = [
        "# Vault context (generated by the SessionStart hook)",
        f"Today is {d.strftime('%A')} {d.isoformat()}. Today's daily note: {lib.rel(path)}",
        "",
        vault.status_text(),
        "",
    ]
    problems = lib.validate_all()
    if problems:
        flat = [f"- {p}: {msg}" for p, msgs in problems.items() for msg in msgs]
        out.append(f"Vault check found {len(flat)} problem(s). Mention them to the user before other work:")
        out += flat[:MAX_PROBLEMS]
        if len(flat) > MAX_PROBLEMS:
            out.append(f"- ... run `{lib.CLI} validate` for all {len(flat)}")
    else:
        out.append("Vault check: OK")
    print("\n".join(out))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # never block a session from starting
        print(f"(vault SessionStart hook failed: {e})")
