"""SessionStart hook: hand Claude the current state so it never has to remember to look.
Whatever this prints is added to Claude's context. The session's kind comes from its cwd:

  vault  inside the vault: project one-liners, the last 10 daily lines and the `validate`
         results (which also catch phone-side edits, that bypass every other hook);
         creates today's daily note.
  repo   inside a clone whose `origin` is a registered repo: the project overview, the
         branch's issue and its stage, the project's last 5 daily lines, its open ideas,
         and the repo's `claudemd-lint` failures and stale-section count.
  else   nothing.

Vault and repo sessions also record what Stop needs: when the session started, the
fingerprints of sealed and closed notes, and (repo) the git state.
GitHub gets 5 seconds in total; nothing here may block a session from starting.
"""
from __future__ import annotations

import re
import sys
import time
from pathlib import Path

sys.dont_write_bytecode = True  # keep __pycache__ out of iCloud
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import claudemd  # noqa: E402
import github  # noqa: E402
import lib  # noqa: E402
import vault  # noqa: E402

MAX_PROBLEMS = 15
GITHUB_SECONDS = 5
CLAUDEMD_SECONDS = 3


def git_state(root: str) -> dict:
    """HEAD and the porcelain status now, so Stop can tell what this session changed."""
    head = github.git("rev-parse", "HEAD", cwd=root, check=False) or None
    return {"head": head, "status": github.status_lines(root)}


def project_lines(pid: str, repos: list[str], n: int) -> list[str]:
    names = "|".join(re.escape(r) for r in repos)
    pat = re.compile(rf"\[\[{re.escape(pid)}\]\]" + (rf"|\b(?:{names})#\d+ " if repos else ""))
    return lib.daily_log_lines(n, lambda ln: bool(pat.search(ln)))


def notes_line(repo: str, issue: str) -> str:
    found = []
    for kind in ("plan", "impl", "retro"):
        p = vault.work_path(repo, issue, kind)
        if p.is_file():
            fm, _, _ = lib.split_frontmatter(lib.read_text(p))
            found.append(f"{kind} ({(fm or {}).get('status', '?')})")
    return ", ".join(found) or "no notes yet"


def stage_line(info: dict, branch: str) -> list[str]:
    m = re.match(rf"^(?:{'|'.join(lib.BRANCH_TYPES)})/([0-9]+)-", branch)
    if not m:
        return [f"Branch {branch or '(none)'} isn't tied to an issue (branches are <type>/<issue>-<slug>)."]
    issue = m.group(1)
    out = [f"Branch {branch} → {info['repo']}#{issue}. Notes: {notes_line(info['repo'], issue)}."]
    github.DEADLINE = time.monotonic() + GITHUB_SECONDS
    try:
        stage, why = vault.stage_of(info["slug"], info["repo"], issue)
        out.append(f"Stage: {stage} ({why}).")
    except Exception as e:  # a slow, offline or signed-out GitHub must never delay a session
        out.append(f"Stage unavailable ({e}).")
    return out


def claudemd_lines(root: str) -> list[str]:
    """claudemd-lint failures and the stale count for this repo's CLAUDE.md,
    time-boxed so a slow or crashing git call never blocks the session (AC8)."""
    github.DEADLINE = time.monotonic() + CLAUDEMD_SECONDS
    try:
        result = claudemd.lint(Path(root))
    except Exception as e:
        return [f"claudemd-lint unavailable ({type(e).__name__}: {e})."]
    finally:
        github.DEADLINE = None
    if not result.errors:
        return [f"claudemd-lint: OK ({result.stale} stale section(s))" if result.stale
               else "claudemd-lint: OK"]
    out = [f"claudemd-lint found {len(result.errors)} problem(s):"]
    out += [f"- {e}" for e in result.errors[:MAX_PROBLEMS]]
    if len(result.errors) > MAX_PROBLEMS:
        out.append(f"- ... run `{lib.CLI} claudemd-lint` for all {len(result.errors)}")
    if result.stale:
        out.append(f"({result.stale} stale section(s); run `{lib.CLI} claudemd-lint` to see them)")
    return out


def repo_context(info: dict, cwd: str) -> list[str]:
    index = lib.Index()
    pid = info["project"]
    fm, body, _ = lib.split_frontmatter(lib.read_text(index.projects[pid]))
    repos = [r.split("/")[-1] for r in (fm or {}).get("repos") or []]
    branch = github.git("rev-parse", "--abbrev-ref", "HEAD", cwd=cwd, check=False)
    ideas = sum(1 for _, ifm in vault.all_ideas()
                if ifm.get("status") == "open" and ifm.get("project") == pid)
    out = [f"# Project context for {info['slug']} (generated by the SessionStart hook)",
           f"## Project overview: [[{pid}]]", body.strip(), "", *stage_line(info, branch), "",
           f"Last daily lines for {pid}:"]
    out += [f"- {ln}" for ln in project_lines(pid, repos, 5)] or ["- (none)"]
    out.append(f"Open ideas for {pid}: {ideas}")
    out.append("")
    out += claudemd_lines(info["root"])
    return out


def vault_context() -> list[str]:
    path, _ = vault.create_daily()
    d = lib.today()
    out = ["# Vault context (generated by the SessionStart hook)",
           f"Today is {d.strftime('%A')} {d.isoformat()}. Today's daily note: {lib.rel(path)}",
           "", vault.status_text(), "", "Last 10 daily lines:"]
    out += [f"- {ln}" for ln in lib.daily_log_lines(10)] or ["- (none)"]
    out.append("")
    problems, warnings = lib.validate_all()
    if problems:
        flat = [f"- {p}: {msg}" for p, msgs in problems.items() for msg in msgs]
        out.append(f"Vault check found {len(flat)} problem(s). Mention them to the user before other work:")
        out += flat[:MAX_PROBLEMS]
        if len(flat) > MAX_PROBLEMS:
            out.append(f"- ... run `{lib.CLI} validate` for all {len(flat)}")
    else:
        out.append("Vault check: OK")
    n_warn = sum(len(m) for m in warnings.values())
    if n_warn:
        out.append(f"({n_warn} vault warning(s); run `{lib.CLI} validate` to see them)")
    return out


def main() -> None:
    lib.setup_io()
    if lib.VAULT is None:
        return
    data = lib.read_hook_input()
    cwd = data.get("cwd")
    info = lib.session_kind(cwd)
    if info["kind"] is None:
        return
    if info["kind"] == "vault":
        vault.create_daily()                # before the line count below
    sid = data.get("session_id", "")
    state = lib.load_state(sid)
    first = "started" not in state          # resume and compact fire SessionStart again
    if first:
        daily = lib.daily_path()
        state.update(started=time.time(), kind=info["kind"], fingerprints=lib.fingerprints(),
                     daily_lines=len(lib.read_text(daily).splitlines()) if daily.exists() else 0)
        if info["kind"] == "repo":
            state.update(repo=info["repo"], project=info["project"], root=info["root"],
                         git=git_state(info["root"]))
        lib.save_state(sid, state)
    out = vault_context() if info["kind"] == "vault" else repo_context(info, cwd)
    print("\n".join(out))


if __name__ == "__main__":
    lib.run_hook(main, "SessionStart", stream=sys.stdout)   # never block a session from starting
